services:

  db:
    image: postgres:15

    restart: always

    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:

    image: dpage/pgadmin4

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8080:80"

    depends_on:
      - db

  flask-app:

    build: .

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - db

volumes:
  postgres_data: